import Head from 'next/head';
import Link from 'next/link'
import { NextPage } from 'next';
import { Title } from 'styles/styledComponents/example';
import { useEffect } from 'react';
import redux from 'data/redux';

const Home: NextPage = () => {
  useEffect(() => {
    redux.errorLog({ payload: { code: 998 }, jkApiName: 'none' });
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next JK Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto p-4 flex flex-col">
        <Link href="/example">
          <a>Go Example Page</a>
        </Link>

        <div className="container-padding">
          <h1 className="h1-title">Create Next JK Web</h1>
        </div>

        <h2 className="title flex-1 items-center flex justify-center mt-10 p-test">
          config is work {process.env.APP_NAME} - {process.env.API_HOST}
        </h2>

        <Title>Test styled component with tailwind config</Title>
      </div>

    </div>
  );
}

export default Home;